#!/bin/bash

alpha='dd'
background='#1e1e2e'
selection='#181825'
comment='#45475a'

yellow='#f9e2af'
orange='#fab387'
red='#f38ba8'
magenta='#cba6f7'
blue='#89b4fa'
cyan='#74c7ec'
green='#a6e3a1'

i3lock \
  --insidever-color=$selection$alpha \
  --insidewrong-color=$selection$alpha \
  --inside-color=$selection$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ring-color=$blue$alpha \
  --line-uses-ring \
  --keyhl-color=$magenta$alpha \
  --bshl-color=$orange$alpha \
  --separator-color=$blue$alpha \
  --verif-color=$green \
  --wrong-color=$red \
  --modif-color=$red \
  --layout-color=$blue \
  --date-color=$blue \
  --time-color=$blue \
  --screen 1 \
  --blur 1 \
  --clock \
  --indicator \
  --time-str="%H:%M:%S" \
  --date-str="%A %e %B %Y" \
  --verif-text="  " \
  --wrong-text="    " \
  --noinput="    " \
  --lock-text="   " \
  --lockfailed="    " \
  --radius=120 \
  --ring-width=10 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys \
 --time-font="CaskaydiaCove Nerd Font" \
 --date-font="CaskaydiaCove Nerd Font" \
 --layout-font="CaskaydiaCove Nerd Font" \
 --verif-font="CaskaydiaCove Nerd Font" \
 --wrong-font="CaskaydiaCove Nerd Font" \

