export FZF_DEFAULT_OPTS=" \
--layout=reverse \
--info=inline-right \
--border=rounded \
--gutter=' ' \
--color=border:4 \
--color=gutter:-1 \
--color=bg+:8,spinner:4,hl:1 \
--color=fg:-1,header:4,info:8,pointer:4 \
--color=marker:2,fg+:-1,prompt:4,hl+:1 \
--color=selected-bg:8 \
--multi"
