general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 0
    on-resume = brightnessctl -r
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 630
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
    on-resume = brightnessctl -r && hyprctl dispatch dpms on
}

# DESKTOP
# Uncomment this profile when using desktop monitors without brightnessctl.
#
# listener {
#     timeout = 900
#     on-timeout = loginctl lock-session
# }
#
# # Turn off displays 5 minutes AFTER lock
# listener {
#     timeout = 1200
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on
# }
#
# # Suspend after 30 minutes
# listener {
#     timeout = 1800
#     on-timeout = systemctl suspend
#     on-resume = hyprctl dispatch dpms on
# }
