# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# General behavior
set -g mouse on
set -g status-position top
set -g default-terminal "tmux-256color"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -g focus-events on
set -sg escape-time 10
setw -g mode-keys vi

# Reload configuration
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Split panes keeping current working directory
bind v split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"
