add_newline = false

[character]
error_symbol = "[➜](bold red)"
success_symbol = "[➜](bold green)"
vicmd_symbol = "[➜](bold yellow)"

[directory]
style = "bold blue"
read_only = ""

[cmd_duration]
format = "[](purple) [$duration]($style) "

[python]
symbol = "󰌠 "

[lua]
symbol = " "

